# Sample localization file for English. Add more files in this directory for other locales.
# See https://github.com/svenfuchs/rails-i18n/tree/master/rails%2Flocale for starting points.

en:
  welcome_back: "Welcome back: "
  company_slogan: "We do property party kits yeah - not like party who stuff it it the bag!"
  edit_google_merchant_settings: "Edit Google Merchant settings"
  google_merchant_title: "Google Merchant title"
  google_merchant_description: "Google Merchant description"
  production_domain: "Production domain"
  google_merchant: "Google Merchant"
  google_merchants_description: "Provides a live feed of active products for Google Merchant" #Not to be confused with the above